[project]
name = "wikipedia-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.9.3",
    "numpy==1.26.4",
    "scikit-learn==1.5.2",
    "sentence-transformers==3.3.1",
    "torch==2.5.1",
    "wikipedia-api==0.7.1",
]
